apiVersion: apps/v1 
kind: Deployment
metadata:
  name: yld-deployment
spec:
  selector:
    matchLabels:
      app: mock-endpoints
  replicas: 3
  template:
    metadata:
      labels:
        app: mock-endpoints
    spec:
      containers:
      - name: mock-endpoints
        image: gururajsubash/mock-endpoints
        ports:
        - containerPort: 80
